import { Address } from 'viem';

export const MAGIC_SQUARE_NUMBER_CONTRACT_ADDRESS =
  '0xbEcF8921E0248827C1c91e153C1965Aa4a7dBAd2';
export const MAGIC_TRIANGLE_CONTRACT_ADDRESS =
  '0xb04d527fCe14F15Ce32BA364305A82Eaf04C26a7';
export const PRIME_NUMBERS_CONTRACT_ADDRESS =
  '0x8aDb0DeD3faa21418783F3EB1AD72bB193e96019';

export const ADDRESSES = [
  MAGIC_SQUARE_NUMBER_CONTRACT_ADDRESS,
  MAGIC_TRIANGLE_CONTRACT_ADDRESS,
  PRIME_NUMBERS_CONTRACT_ADDRESS
] as Array<Address>;

export const CONTRACT_METADATA: any = {
  [MAGIC_SQUARE_NUMBER_CONTRACT_ADDRESS]: {
    NAME: 'MAGIC_SQUARE_NUMBER',
    PLACEHOLDER: 'ENTER MAGIC SQUARE PROOF',
    LOGO_URL: '/square_numbers.png',
    SOLUTION: '{31,73,7,13,37,61,67,1,43}'
  },
  [MAGIC_TRIANGLE_CONTRACT_ADDRESS]: {
    NAME: 'MAGIC_TRIANGLE_NUMBER',
    PLACEHOLDER: 'ENTER MAGIC TRIANGLE PROOF',
    LOGO_URL: '/triangle_numbers.png'
  },
  [PRIME_NUMBERS_CONTRACT_ADDRESS]: {
    LOGO_URL: '/prime.png',
    NAME: 'PRIME_NUMBERS',
    PLACEHOLDER: 'ENTER PRIME NUMBERS PROOF'
  }
};
